### ISSUE TITLE
Projects building

### ISSUE THREAD

**Issue by hammalas** [rlogiacco/Natural#52]
Could you pleease explain more how to build the projects using Eclipse ?

**Comment by rlogiacco** [comment]
Have you already read the wiki? https://github.com/rlogiacco/Natural/wiki/Contribute

Do you have any specific issue you are facing?

**Comment by hammalas** [comment]
I have cloned the repo, then I installed xtext plugin on eclipse (first time I use this ). When I Run MWE2 Workflow I hav this error : A JNI error has occured, please check your installation and try again.

**Comment by rlogiacco** [comment]
Well, I suggest to start googling for that and see if you get any meaningful advice. I could do a verification on my computer, but since the error seems relative to native code (JNI) we will also have to consider operating system differences...

- which OS are you on?
- what platform type are you using, 32 or 64 bit?
- which specific version of Java are you using?
- which specific version of Eclipse did you install?
- which version of Xtext are you using?

It is possible it's a version conflict, a similar problem has been reported on #48 .

**Comment by hammalas** [comment]
I'm using windows7 64 bits, java 8, Eclipse mars and xtext last version
2.11.0

2017-05-03 11:57 GMT+02:00 Roberto Lo Giacco <notifications@github.com>:

**Comment by hammalas** [comment]
xtext version issue
